-- SUPERSEDED by lib/levels.lua (the generalized, data-driven level engine).
-- Level 1 and the shared per-level infrastructure now live in levels.lua.
-- This file is intentionally empty so the bundler does not double-define globals.
-- (Kept as a tombstone; safe to delete.)
